### PR TITLE
Update config for xdebug 3

### PR DESCRIPTION
**Pull request by ihor-sviziev**

### CODE REVIEW

**Comment by danielozano** [comment]
Hi @ihor-sviziev. First of all thanks a lot again for your contribution!

I've a question: those changes are backward incompatible with old phpstorm versions (non-xdebug 3 environments)?

Thanks!

**Comment by ihor-sviziev** [comment]
@danielozano seems like it's not backward compatible, BUT if you'll try to compile these dockerfiles right now - it will have installed xdebug 3, so that's why I did it in a backward-incompatible way

**Comment by danielozano** [comment]
Ok! I'm not worried about the image then, changes will only be applied on new builds with new config.

But the changes at [dockergento](https://github.com/ModestCoders/magento2-dockergento/pull/83/files) could be applied with an old image version right?

(I'm just trying to understand the scope and the consecuences of the change)

**Comment by ihor-sviziev** [comment]
In theory, we might check if there are new options and show them, with a fallback to old ones, but not sure how to do that.
Now it looks like this:
image

**Comment by ihor-sviziev** [comment]
Hi @danielozano,
I just did changes in dockergento in order to support old & new config versions in https://github.com/ModestCoders/magento2-dockergento/pull/83.
What do you thing about it?

**Comment by danielozano** [comment]
Hi @ihor-sviziev thanks a lot again and sorry for the late response (I had some days off). I'm going to test with an old project, but I think it's our better option rigth now.

**Comment by danielozano** [comment]
Hi again @ihor-sviziev.

I've been testing and the dockergento changes work like a charm! But the changes at the *.ini files are not working for x-debug < 3.

I've thought about 2 options:
 - (dockergento) Script detects xdebug versions, and loads the config in order to version detected.
 - (dockerfiles) Include both settigs (for v3 and older) inside .ini file.

I've tested it with xdebug 2.9 and its working, but I'm not sure if it the cleanest option...
```
xdebug.idekey=PHPSTORM
;[xdebug >= 3]
xdebug.start_with_request=yes
xdebug.discover_client_host=false
xdebug.mode=debug
xdebug.client_host=host.docker.internal
xdebug.max_nesting_level=500

;[xdebug < 3]
xdebug.remote_enable=1
xdebug.remote_host=host.docker.internal
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.remote_port=9001
xdebug.max_nesting_level=500
```

Maybe I'm missing something when testing it for 2.9 (maybe some config for ports?)

What do you think?

Thanks a lot!

**Comment by ihor-sviziev** [comment]
Looks good to me. Could you add your changes and merge them?

**Comment by danielozano** [comment]
Sure! I'm going to give it a try, then I will merge your changes and add mine!

**Pull request merged**
